repositories:
  - name: plaud-flutter-cn
    path: plaud-flutter-cn
    url: git@github.com:Plaud-AI/plaud-flutter-cn.git
  - name: plaud-flutter-global
    path: plaud-flutter-global
    url: git@github.com:Plaud-AI/plaud-flutter-global.git
  - name: plaud-flutter-common
    path: plaud-flutter-common
    url: git@github.com:Plaud-AI/plaud-flutter-common.git
  - name: plaud-android
    path: plaud-android
    url: git@github.com:Plaud-AI/plaud-android.git
  - name: plaud-ios
    path: plaud-ios
    url: git@github.com:Plaud-AI/plaud-ios.git

